### ISSUE TITLE
White/grey horses

### ISSUE THREAD

**Issue by EqKay** [sekelsta/horse-colors#25]
Whenever I spawn/breed a gray/white horse, it starts dying. It has green potion effects around it and it's not poison because it dies from it? I've checked their data via the books, the horses aren't related, therefore we aren't inbreeding and their health shows that they're healthy and it happens every single time I get a gray/white horse and it's kind of annoying.

**Comment by sekelsta** [comment]
Your foals have lethal white syndome, caused by two copies of the frame overo gene. Lethal white foals come from breeding two frame overo horses together, and die shortly after birth due to an underdeveloped digestive system.
Gray is dominant, so if you want gray you need to find a gray horse (will have G at Gray). Dominant white is also dominant so to get that you'd need W at KIT, but you can also get sabino white from breeding two sabino horses (SB1 at KIT) together. The gray, dominant white, and sabino white horses can all be healthy, unlike the lethal white overo.
